version: '3.4'

services:
  hometg.api:
    image: ${DOCKER_REGISTRY-}hometgapi
    build:
      context: .
      dockerfile: HomeTG.API/Dockerfile

  hometg:
    image: ${DOCKER_REGISTRY-}hometg
    build:
      context: .
      dockerfile: HomeTGCollection/Dockerfile

