version: '3'
services:
  hometg-api:
    build:
      dockerfile: HomeTGCollection/Dockerfile
    pull_policy: build
    ports:
      - "5234:80"
    volumes:
      - /config/hometg:/usr/share/hometg
    restart: always
