version: '3.4'

services:
  hometg:
    build:
      context: .
      dockerfile: HomeTG.API/Dockerfile
    pull_policy: build
    ports:
      - "5234:80"
    volumes:
      - /config/hometg:/usr/share/hometg
    environment:
      "ASPNETCORE_ENVIRONMENT": "linux"
      # Optional way to overwrite database connection
      # "ConnectionStrings:DefaultConnection": "Data Source=/usr/share/hometg/Collection.db"
    networks:
      - public
      - private
    restart: always

  hometg-react:
    build:
      context: .
      dockerfile: HomeTG.React/Dockerfile
    environment:
      REACT_APP_PROXY_HOST: "http://hometg"
      WDS_SOCKET_PORT: 0
    pull_policy: build
    ports:
      - "5235:3000"
    networks:
      - public
    restart: unless-stopped

networks:
  public:
  private:
