version: '3.4'

services:
  hometg:
    build:
      context: .
      dockerfile: HomeTGCollection/Dockerfile
    pull_policy: build
    ports:
      - "5234:80"
    volumes:
      - /config/hometg:/usr/share/hometg
    restart: always
